version: '3.8'

services:
  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    
  api-gateway:
    build: ./api-gateway  
    ports:
      - "3000:3000"
    depends_on:
      - ml-service
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
